name: CI/CD VOD Platform

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/health || exit 1"
          --health-interval 5s
          --health-retries 20
          --health-timeout 2s
        env:
          SERVICES: s3
          DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java for SonarCloud
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true
        with:
          args: >
            -Dsonar.projectKey=Victfigueroa_vod-cloud-devops
            -Dsonar.organization=victfigueroa
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
        shell: bash

      - name: Run Python Unit Tests
        run: python3 -m unittest discover
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Wait for LocalStack to be ready
        run: |
          until curl -s http://localhost:4566/health | grep '"initialized":true'; do
            echo "Waiting for LocalStack..."
            sleep 5
          done
        shell: bash

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
        shell: bash

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
        shell: bash

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
        shell: bash

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
          publish_branch: gh-pages
